<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ozelsayfalar extends Model
{
    use HasFactory;

    protected $table = 'ozelsayfalar';

    protected $fillable = [
        'sayfa_adi',
        'ss_soru',
        'ss_cevap',
        'ss_resim',
        'ss_icerik',
        'ss_icerik1',
        'ss_icerik2',
        'ss_icerik3',
        'ss_icerik4',
        'ss_icerik5',
        'referans_video',
        'referans_resim',
        'referans_yorum',
        'referans_icerik',
        'referans_icerik1',
        'referans_icerik2',
        'referans_icerik3',
        'referans_icerik4',
        'referans_icerik5',
        'partner_video',
        'partner_resim',
        'partner_yorum',
        'partner_icerik',
        'partner_icerik1',
        'partner_icerik2',
        'partner_icerik3',
        'partner_icerik4',
        'partner_icerik5',
        'slider_resim',
        'slider_baslik',
        'slider_aciklama',
        'slider_icerik1',
        'slider_icerik2',
        'slider_icerik3',
        'slider_icerik4',
        'slider_icerik5',
        'Gizlilik_icerik',
        'iletişim_adresi1',
        'iletişim_adresi2',
        'iletişim_adresi3',
        'iletişim_adresi4',
        'iletişim_adresi5',
        'iletişim_mail',
        'iletişim_mail1',
        'iletişim_mail2',
        'iletişim_mail3',
        'iletişim_mail4',
        'iletişim_mail5',
        'iletişim_telefon1',
        'iletişim_telefon2',
        'iletişim_telefon3',
        'iletişim_telefon4',
        'iletişim_telefon5',
        'ekip_üye_ad',
        'ekip_üye_mail',
        'ekip_üye_resim',
        'ekip_üye_icerik',
        'ekip_üye_icerik1',
        'ekip_üye_icerik2',
        'ekip_üye_icerik3',
        'ekip_üye_icerik4',
        'ekip_üye_icerik5',
        'proje_adı',
        'proje_resim',
        'proje_içerik1',
        'proje_içerik2',
        'proje_içerik3',
        'proje_içerik4',
        'proje_içerik5',
        'içerik',
        'içerik1',
        'içerik2',
        'içerik3',
        'içerik4',
    ];
}
