<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sayfa extends Model
{
    use HasFactory;

    protected $table = 'sayfalar';

    protected $fillable = [
        'sayfa_adi',
        'sayfa_icerik',
        'sayfa_icerik1',
        'sayfa_icerik2',
        'sayfa_icerik3',
        'sayfa_icerik4',
        'sayfa_icerik5',
        'sayfa_icerik6',
        'sayfa_icerik7',
        'sayfa_icerik8',
        // 'sayfa_icerik9',
        // 'sayfa_icerik10',
        'sayfa_icerik11',
        'sayfa_icerik12',
        'sayfa_icerik13',
        'sayfa_icerik14',
        'sayfa_icerik15',
        'sayfa_icerik16',
        'sayfa_icerik17',
        'sayfa_icerik18',
        'sayfa_icerik19',
        'sayfa_icerik20',
        'sayfa_icerik21',
        'sayfa_icerik22',
        'sayfa_icerik23',
        'sayfa_icerik24',
        'sayfa_icerik25',
        'sayfa_icerik26',
        'sayfa_icerik27',
        'sayfa_icerik28',
        'sayfa_icerik29',
        'sayfa_icerik30',
        'resimler',
        'resim1',
        'resim2',
        'resim3',
        'resim4',
        'resim5',
        'resim6',
        'resim7',
        'resim8',
        'resim9',
        'resim10',
        'resim11',
        'resim12',
        'resim13',
        'resim14',
        'resim15',
        'resim16',
        'resim17',
        'resim18',
        'resim19',
        'resim20',
        'resim21',
        'resim22',
        'resim23',
        'resim24',
        'resim25',
        'resim26',
        'resim27',
        'resim28',
        'resim29',
        'resim30',
        'video',
        'video2',
        'video3',
        'video4',
        'video5',
        'video6',
        'video7',
        'video8',
        'video9',
        'video10',
        'video11',
        'video12',
        'video13',
        'video14',
        'video15',
        'video16',
        'video17',
        'video18',
        'video19',
        'video20',
        'video21',
        'video22',
        'video23',
        'video24',
        'video25',
        'video26',
        'video27',
        'video28',
        'video29',
        'video30',
    ];
}
